// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using simple_crud.Data;

#nullable disable

namespace simple_crud.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("simple_crud.Models.Etudiant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsExclut")
                        .HasColumnType("bit");

                    b.Property<double>("MoyenneGenerale")
                        .HasColumnType("float");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Etudiants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateNaissance = new DateTime(2022, 5, 28, 15, 47, 10, 762, DateTimeKind.Local).AddTicks(5307),
                            IsExclut = false,
                            MoyenneGenerale = 17.5,
                            Nom = "nom_1",
                            Prenom = "prenom_1"
                        },
                        new
                        {
                            Id = 2,
                            DateNaissance = new DateTime(2022, 5, 28, 15, 47, 10, 762, DateTimeKind.Local).AddTicks(5329),
                            IsExclut = false,
                            MoyenneGenerale = 16.5,
                            Nom = "nom_2",
                            Prenom = "prenom_2"
                        },
                        new
                        {
                            Id = 3,
                            DateNaissance = new DateTime(2022, 5, 28, 15, 47, 10, 762, DateTimeKind.Local).AddTicks(5330),
                            IsExclut = false,
                            MoyenneGenerale = 15.5,
                            Nom = "nom_3",
                            Prenom = "prenom_3"
                        },
                        new
                        {
                            Id = 4,
                            DateNaissance = new DateTime(2022, 5, 28, 15, 47, 10, 762, DateTimeKind.Local).AddTicks(5331),
                            IsExclut = false,
                            MoyenneGenerale = 14.5,
                            Nom = "nom_4",
                            Prenom = "prenom_4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
